package de.aidger.view.reports;

import static de.aidger.utils.Translation._;

import javax.swing.table.DefaultTableModel;

/**
 * A JPanel which has the courses of a group in it.
 * 
 * @author aidGer Team
 */
@SuppressWarnings("serial")
public class BalanceReportGroupPanel extends javax.swing.JPanel {

    /**
     * The name of the group.
     */
    private final String group;

    /**
     * The table model of the content table.
     */
    private final DefaultTableModel groupTableModel = new DefaultTableModel(
        null, new String[] { _("Title"), _("Part"), _("Lecturer"),
                _("Target Audience"), _("Planned AWS"), _("Basic needed AWS"),
                _("Budget costs from student fees"),
                _("Budget costs from resources") }) {
        boolean[] canEdit = new boolean[] { false, false, false, false, false,
                false, false, false };

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };

    /**
     * Initializes a new BalanceReportGroupViewer.
     * 
     * @param group
     *            The name of the group.
     */
    public BalanceReportGroupPanel(String group) {
        this.group = group;
        initComponents();
        contentPanel.add(contentTable.getTableHeader(),
            java.awt.BorderLayout.NORTH);
    }

    /**
     * Adds a course to the table.
     * 
     * @param course
     *            The course to be added to the table.
     */
    public void addCourse(Object[] course) {
        groupTableModel.addRow(course);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupNameLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        contentTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        groupNameLabel.setText(_("Group") + (" ") + group);
        add(groupNameLabel, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new java.awt.BorderLayout());

        contentTable.setModel(groupTableModel);
        contentPanel.add(contentTable, java.awt.BorderLayout.CENTER);

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JTable contentTable;
    private javax.swing.JLabel groupNameLabel;
    // End of variables declaration//GEN-END:variables

}
