package de.aidger.view.reports;

import static de.aidger.utils.Translation._;

import javax.swing.JPanel;

/**
 * A JPanel which holds all the groups of a semester.
 * 
 * @author aidGer Team
 */
public class BalanceReportSemesterViewer extends javax.swing.JPanel {

    /**
     * The name of the semester.
     */
    private final String name;

    /**
     * Initializes a new BalanceReportSemesterViewer.
     * 
     * @param semester
     *            The name of the semester.
     */
    public BalanceReportSemesterViewer(String semester) {
        this.name = semester;
        initComponents();
    }

    /**
     * Adds a new group panel to the semester panel.
     * 
     * @param panel
     *            The panel to be added
     */
    public void createGroup(JPanel panel) {
        this.add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(_("Semester")
                + (" ") + name));
        setLayout(new java.awt.GridLayout(0, 1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
