/*
 * This file is part of the aidGer project.
 *
 * Copyright (C) 2010-2011 The aidGer Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package de.aidger.view.reports;

import static de.aidger.utils.Translation._;

import javax.swing.ImageIcon;

import de.aidger.view.tabs.ReportTab;

/**
 * This class contains one filter, with its type and value.
 * 
 * @author aidGer Team
 */
@SuppressWarnings("serial")
public class BalanceFilterPanel extends javax.swing.JPanel {

    /**
     * The name of this filter panel.
     */
    private String name = null;

    /**
     * The balanceViewerTab to which this panel belongs.
     */
    private ReportTab viewerTab = null;

    /**
     * Initializes a new BalanceFilterPanel with the given filter.
     * 
     * @param type
     *            The type of the filter.
     * @param value
     *            The value of the filter.
     * @param balanceViewerTab
     *            The balance viewer tab to which this panel belongs.
     */
    public BalanceFilterPanel(String name, String value, ReportTab viewerTab) {
        this.viewerTab = viewerTab;
        this.name = name;
        initComponents();
        filterNameLabel.setText(name);
        filterLabel.setText(value);
        budgetFilterLabel.setVisible(false);
    }

    /**
     * Sets the text in the filter label.
     * 
     * @param name
     *            The name to set it to.
     */
    public void setFilterLabel(String name) {
        filterLabel.setText(name);
    }

    /**
     * Sets the text in the budget filter label.
     * 
     * @param name
     *            The name to set it to.
     */
    public void setBudgetLabel(String name) {
        budgetFilterLabel.setText(name);
        budgetFilterLabel.setVisible(false);
        budgetFilterLabel.setVisible(true);
    }

    @Override
    public String getName() {
        return name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeFilterButton = new javax.swing.JButton();
        filterNameDescriptionLabel = new javax.swing.JLabel();
        filterNameLabel = new javax.swing.JLabel();
        filterLabel = new javax.swing.JLabel();
        budgetFilterLabel = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        removeFilterButton.setIcon(new ImageIcon(getClass().getResource(
            "/de/aidger/res/icons/minus-small.png")));
removeFilterButton.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        removeFilterButtonActionPerformed(evt);
    }
    });
    add(removeFilterButton);

    filterNameDescriptionLabel.setText(_("Filter") + ":");
    add(filterNameDescriptionLabel);

    filterNameLabel.setText("");
    add(filterNameLabel);

    filterLabel.setText("");
    add(filterLabel);
    add(budgetFilterLabel);
    }// </editor-fold>//GEN-END:initComponents

    private void removeFilterButtonActionPerformed(
            java.awt.event.ActionEvent evt) {// GEN-FIRST:event_removeFilterButtonActionPerformed
        viewerTab.removeFilter(name, filterLabel.getText());
        viewerTab.removeFilterPanel(this);
    }// GEN-LAST:event_removeFilterButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel budgetFilterLabel;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JLabel filterNameDescriptionLabel;
    private javax.swing.JLabel filterNameLabel;
    private javax.swing.JButton removeFilterButton;
    // End of variables declaration//GEN-END:variables

}
