package de.aidger.view.reports;

import static de.aidger.utils.Translation._;
import de.aidger.view.tabs.BalanceViewerTab;

/**
 * This class contains one filter, with its type and value.
 * 
 * @author aidGer Team
 */
public class BalanceFilterPanel extends javax.swing.JPanel {

    /**
     * The balanceViewerTab to which this panel belongs.
     */
    private BalanceViewerTab balanceViewerTab = null;

    /**
     * The type of this filter. 0 is group, 1 is lecturer, 2 is target audience.
     */
    private int type = -1;

    /**
     * Initializes a new BalanceFilterPanel with the given filter.
     * 
     * @param type
     *            The type of the filter.
     * @param value
     *            The value of the filter.
     * @param balanceViewerTab
     *            The balance viewer tab to which this panel belongs.
     */
    public BalanceFilterPanel(int type, String value,
            BalanceViewerTab balanceViewerTab) {
        if (this.balanceViewerTab == null) {
            this.balanceViewerTab = balanceViewerTab;
        }
        this.type = type;
        initComponents();
        switch (type) {
        case 0:
            filterNameLabel.setText(_("Group"));
            break;
        case 1:
            filterNameLabel.setText(_("Lecturer"));
            break;
        case 2:
            filterNameLabel.setText(_("Target Audience"));
        }
        filterLabel.setText(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterNameDescriptionLabel = new javax.swing.JLabel();
        filterNameLabel = new javax.swing.JLabel();
        filterLabel = new javax.swing.JLabel();
        removeFilterButton = new javax.swing.JButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        filterNameDescriptionLabel.setText(_("Filter") + ":");
        add(filterNameDescriptionLabel);

        filterNameLabel.setText("");
        add(filterNameLabel);

        filterLabel.setText("");
        add(filterLabel);

        removeFilterButton.setText("-");
        removeFilterButton
            .addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    removeFilterButtonActionPerformed(evt);
                }
            });
        add(removeFilterButton);
    }// </editor-fold>//GEN-END:initComponents

    private void removeFilterButtonActionPerformed(
            java.awt.event.ActionEvent evt) {// GEN-FIRST:event_removeFilterButtonActionPerformed
        balanceViewerTab.removeFilter(type, filterLabel.getText());
        balanceViewerTab.removeFilterPanel(this);
    }// GEN-LAST:event_removeFilterButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel filterLabel;
    private javax.swing.JLabel filterNameDescriptionLabel;
    private javax.swing.JLabel filterNameLabel;
    private javax.swing.JButton removeFilterButton;
    // End of variables declaration//GEN-END:variables

}
