package de.aidger.view.reports;

import static de.aidger.utils.Translation._;

/**
 * A JPanel which has the courses of a group in it.
 * 
 * @author aidGer Team
 */
public class BalanceReportGroupCreator extends javax.swing.JPanel {

    /**
     * The name of the group.
     */
    private final String name;

    /**
     * Initializes a new BalanceReportGroupCreator and adds the table for
     * displaying the courses.
     * 
     * @param name
     *            The name of the group.
     */
    public BalanceReportGroupCreator(String name) {
        this.name = name;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(_("Group") + " "
                + name));
        setLayout(new java.awt.GridLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null } },
                new String[] { "java.lang.Object@38f3cbe6",
                        "java.lang.Object@38f3cbe6",
                        "java.lang.Object@38f3cbe6",
                        "java.lang.Object@38f3cbe6",
                        "java.lang.Object@38f3cbe6",
                        "java.lang.Object@38f3cbe6",
                        "java.lang.Object@38f3cbe6",
                        "java.lang.Object@38f3cbe6" }) {
            boolean[] canEdit = new boolean[] { false, false, false, false,
                    false, false, false, false };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(_("Title"));
        jTable1.getColumnModel().getColumn(1).setHeaderValue(_("Part"));
        jTable1.getColumnModel().getColumn(2).setHeaderValue(_("Lecturer"));
        jTable1.getColumnModel().getColumn(3).setHeaderValue(
                _("Target Audience"));
        jTable1.getColumnModel().getColumn(4).setHeaderValue(_("Planned AWS"));
        jTable1.getColumnModel().getColumn(5).setHeaderValue(_("Basic AWS"));
        jTable1.getColumnModel().getColumn(6).setHeaderValue(
                _("Budget costs from student fees"));
        jTable1.getColumnModel().getColumn(7).setHeaderValue(
                _("Budget costs from resources"));

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
