package de.aidger.view.forms;

import static de.aidger.utils.Translation._;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.text.JTextComponent;

import de.aidger.model.models.Assistant;
import de.aidger.model.models.Contract;
import de.aidger.model.models.Course;
import de.aidger.model.models.Employment;
import de.aidger.view.UI;
import de.aidger.view.forms.HourlyWageEditorForm.Qualification;
import de.aidger.view.utils.AutoCompletion;
import de.unistuttgart.iste.se.adohive.exceptions.AdoHiveException;
import de.unistuttgart.iste.se.adohive.model.IAssistant;
import de.unistuttgart.iste.se.adohive.model.IContract;
import de.unistuttgart.iste.se.adohive.model.ICourse;

/**
 * A form used for editing / creating new employments.
 * 
 * @author aidGer Team
 */
@SuppressWarnings("serial")
public class EmploymentEditorForm extends JPanel {

    /**
     * Constructs an employment editor tab.
     * 
     * @param employment
     *            The employment that will be edited
     */
    @SuppressWarnings("unchecked")
    public EmploymentEditorForm(Employment employment) {
        initComponents();

        btnContractAdd.setIcon(new ImageIcon(getClass().getResource(
            "/de/aidger/view/icons/plus-small.png")));
        btnContractAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                UI.displayError("Hallo Phil :-)");
            }
        });

        cmbAssistant.setEditable(true);
        cmbCourse.setEditable(true);
        cmbContract.setEditable(true);

        ((JTextComponent) cmbAssistant.getEditor().getEditorComponent())
            .setDocument(new AutoCompletion(cmbAssistant));
        ((JTextComponent) cmbCourse.getEditor().getEditorComponent())
            .setDocument(new AutoCompletion(cmbCourse));
        ((JTextComponent) cmbContract.getEditor().getEditorComponent())
            .setDocument(new AutoCompletion(cmbContract));

        try {
            List<IAssistant> assistants = (new Assistant()).getAll();

            for (IAssistant assistant : assistants) {
                cmbAssistant.addItem(new Assistant(assistant) {
                    @Override
                    public String toString() {
                        return getFirstName() + " " + getLastName();
                    }
                });
            }

            List<ICourse> courses = (new Course()).getAll();

            for (ICourse course : courses) {
                cmbCourse.addItem(new Course(course) {
                    @Override
                    public String toString() {
                        return getDescription() + " (" + getSemester() + ", "
                                + getLecturer() + ")";
                    }
                });
            }

            List<IContract> contracts = (new Contract()).getAll();

            for (IContract contract : contracts) {
                cmbContract.addItem(new Contract(contract) {
                    @Override
                    public String toString() {
                        return getType() + " (" + getStartDate() + " - "
                                + getEndDate() + ")";
                    }
                });
            }

        } catch (AdoHiveException e) {
        }
    }

    /**
     * Get the remarks regarding the employment.
     * 
     * @return The remarks regarding the employment
     */
    public String getRemark() {
        return txtRemark.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblAssistant = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        lblContract = new javax.swing.JLabel();
        cmbAssistant = new javax.swing.JComboBox();
        cmbCourse = new javax.swing.JComboBox();
        cmbContract = new javax.swing.JComboBox();
        btnContractAdd = new javax.swing.JButton();
        lblCostUnit = new javax.swing.JLabel();
        lblQualification = new javax.swing.JLabel();
        lblRemark = new javax.swing.JLabel();
        txtCostUnit = new javax.swing.JTextField();
        txtRemark = new javax.swing.JTextField();
        cmbQualification = new javax.swing.JComboBox();

        setLayout(new java.awt.GridBagLayout());

        lblAssistant.setText(_("Assistant"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lblAssistant, gridBagConstraints);

        lblCourse.setText(_("Course"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lblCourse, gridBagConstraints);

        lblContract.setText(_("Contract"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lblContract, gridBagConstraints);

        cmbAssistant.setMinimumSize(new java.awt.Dimension(200, 25));
        cmbAssistant.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(cmbAssistant, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(cmbCourse, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(cmbContract, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(btnContractAdd, gridBagConstraints);

        lblCostUnit.setText(_("Cost unit"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 10);
        add(lblCostUnit, gridBagConstraints);

        lblQualification.setText(_("Qualification"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 10);
        add(lblQualification, gridBagConstraints);

        lblRemark.setText(_("Remark"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 10);
        add(lblRemark, gridBagConstraints);

        txtCostUnit.setMinimumSize(new java.awt.Dimension(200, 25));
        txtCostUnit.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(txtCostUnit, gridBagConstraints);

        txtRemark.setMinimumSize(new java.awt.Dimension(200, 25));
        txtRemark.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(txtRemark, gridBagConstraints);

        cmbQualification.setModel(new javax.swing.DefaultComboBoxModel(
            Qualification.values()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(cmbQualification, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContractAdd;
    private javax.swing.JComboBox cmbAssistant;
    private javax.swing.JComboBox cmbContract;
    private javax.swing.JComboBox cmbCourse;
    private javax.swing.JComboBox cmbQualification;
    private javax.swing.JLabel lblAssistant;
    private javax.swing.JLabel lblContract;
    private javax.swing.JLabel lblCostUnit;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblQualification;
    private javax.swing.JLabel lblRemark;
    private javax.swing.JTextField txtCostUnit;
    private javax.swing.JTextField txtRemark;
    // End of variables declaration//GEN-END:variables

}
