package de.aidger.view.tabs;

import static de.aidger.utils.Translation._;

import java.util.List;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;

import de.aidger.controller.ActionNotFoundException;
import de.aidger.controller.ActionRegistry;
import de.aidger.controller.actions.ActivityReportGenerateAction;
import de.aidger.model.models.Assistant;
import de.aidger.model.reports.ActivityEmployment;
import de.aidger.utils.reports.ActivityReportHelper;
import de.aidger.view.UI;
import de.unistuttgart.iste.se.adohive.exceptions.AdoHiveException;
import de.unistuttgart.iste.se.adohive.model.IAssistant;

/**
 * This class is used to display the activity report of one assistant.
 * 
 * @author aidGer Team
 */
public class ActivityReportViewerTab extends Tab {

    /**
     * The table model of the content table.
     */
    private final DefaultTableModel contentTableModel = new DefaultTableModel(
        null, new String[] { _("Period"), _("Course"), _("Extent") }) {

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    };

    private Vector<IAssistant> assistants;

    /** Creates new form ActivityReportViewerTab */
    public ActivityReportViewerTab() {
        initComponents();
        fillAssistants();
        try {
            generateButton.setAction(ActionRegistry.getInstance().get(
                ActivityReportGenerateAction.class.getName()));
        } catch (ActionNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    private void clearTable() {
        while (contentTableModel.getRowCount() > 0) {
            contentTableModel.removeRow(0);
        }
    }

    public void createReport(Assistant assistant) {
        clearTable();
        ActivityReportHelper reportHelper = new ActivityReportHelper();
        Vector<ActivityEmployment> activityEmployments = reportHelper
            .getEmployments(assistant);
        for (ActivityEmployment activityEmployment : activityEmployments) {
            addRow(reportHelper.getEmploymentArray(activityEmployment));
        }
    }

    public Assistant getSelectedAssistant() {
        return new Assistant(assistants.get(assistantComboBox
            .getSelectedIndex()));
    }

    private void fillAssistants() {
        List<IAssistant> fillingAssistants;
        assistants = new Vector<IAssistant>();
        try {
            fillingAssistants = new Assistant().getAll();
            for (IAssistant assistant : fillingAssistants) {
                assistantComboBox.addItem(assistant.getFirstName() + " "
                        + assistant.getLastName());
                assistants.add(assistant);
            }
        } catch (AdoHiveException e) {
            UI.displayError(e.toString());
        }
    }

    private void addRow(Object[] rowObject) {
        contentTableModel.addRow(rowObject);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        assistantLabel = new javax.swing.JLabel();
        assistantComboBox = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        generateButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        exportButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        contentPanel = new javax.swing.JPanel();
        assistantPanel = new javax.swing.JPanel();
        assistantNameLabel = new javax.swing.JLabel();
        assistantNameContentLabel = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        assistantLabel.setText(_("Assistant") + ":");
        jToolBar1.add(assistantLabel);

        jToolBar1.add(assistantComboBox);
        jToolBar1.add(jSeparator2);

        generateButton.setText(_("Generate"));
        generateButton.setFocusable(false);
        generateButton
            .setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        generateButton
            .setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(generateButton);
        jToolBar1.add(jSeparator3);

        exportButton.setText(_("Export"));
        exportButton.setFocusable(false);
        exportButton
            .setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(exportButton);
        jToolBar1.add(jSeparator4);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new java.awt.BorderLayout());

        assistantPanel.setLayout(new java.awt.FlowLayout(
            java.awt.FlowLayout.LEFT));

        assistantNameLabel.setText(_("Assistant name") + ":");
        assistantPanel.add(assistantNameLabel);
        assistantPanel.add(assistantNameContentLabel);

        contentPanel.add(assistantPanel, java.awt.BorderLayout.PAGE_START);

        tablePanel.setLayout(new java.awt.GridLayout());

        jTable1.setModel(contentTableModel);
        jScrollPane1.setViewportView(jTable1);

        tablePanel.add(jScrollPane1);

        contentPanel.add(tablePanel, java.awt.BorderLayout.CENTER);

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox assistantComboBox;
    private javax.swing.JLabel assistantLabel;
    private javax.swing.JLabel assistantNameContentLabel;
    private javax.swing.JLabel assistantNameLabel;
    private javax.swing.JPanel assistantPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton exportButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel tablePanel;

    // End of variables declaration//GEN-END:variables
    /*
     * (non-Javadoc)
     * 
     * @see de.aidger.view.tabs.Tab#getTabName()
     */
    @Override
    public String getTabName() {
        // TODO Auto-generated method stub
        return null;
    }

}
