package de.aidger.view.tabs;

import static de.aidger.utils.Translation._;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

import de.aidger.utils.controlling.ControllingHelper;

/**
 * This class is used to display the controlling report.
 * 
 * @author aidGer Team
 */
public class ControllingViewerTab extends Tab {

    /**
     * The table model of the content table.
     */
    private final DefaultTableModel controllingTableModel = new DefaultTableModel(
        null, new String[] { _("Assistant") }) {

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    };

    /** Creates new form ControllingViewerTab */
    public ControllingViewerTab() {
        initComponents();
        createYearItems();
    }

    private void createYearItems() {
        int[] years = new ControllingHelper().getEmploymentYears();
        Object[] yearObjects = new Object[years.length];
        for (int i = 0; i < yearObjects.length; i++) {
            yearObjects[i] = years[i];
        }
        yearComboBox.setModel(new DefaultComboBoxModel(yearObjects));
        createMonthItems((Integer) yearComboBox.getSelectedItem());
    }

    private void createMonthItems(int year) {
        if (yearComboBox.getSelectedIndex() >= 0) {
            monthComboBox.removeAllItems();
            int[] months = new ControllingHelper().getYearMonths(year);
            Object[] monthObjects = new Object[months.length];
            for (int i = 0; i < monthObjects.length; i++) {
                monthObjects[i] = months[i];
            }
            monthComboBox.setModel(new DefaultComboBoxModel(monthObjects));
            createFundsItems(year, (Integer) monthComboBox.getSelectedItem());
        }
    }

    private void createFundsItems(int year, int month) {
        if (monthComboBox.getSelectedIndex() >= 0) {
            fundsComboBox.removeAllItems();
            int[] funds = new ControllingHelper().getFunds(year, month);
            Object[] fundsObjects = new Object[funds.length];
            for (int i = 0; i < fundsObjects.length; i++) {
                fundsObjects[i] = funds[i];
            }
            fundsComboBox.setModel(new DefaultComboBoxModel(fundsObjects));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        yearLabel = new javax.swing.JLabel();
        yearComboBox = new javax.swing.JComboBox();
        monthLabel = new javax.swing.JLabel();
        monthComboBox = new javax.swing.JComboBox();
        fundsLabel = new javax.swing.JLabel();
        fundsComboBox = new javax.swing.JComboBox();
        generateButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        yearLabel.setText(_("Year") + ":");
        jToolBar1.add(yearLabel);

        yearComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearComboBoxItemStateChanged(evt);
            }
        });
        jToolBar1.add(yearComboBox);

        monthLabel.setText(_("Month") + ":");
        jToolBar1.add(monthLabel);

        monthComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthComboBoxItemStateChanged(evt);
            }
        });
        jToolBar1.add(monthComboBox);

        fundsLabel.setText(_("Funds") + ":");
        jToolBar1.add(fundsLabel);

        jToolBar1.add(fundsComboBox);

        generateButton.setText(_("Generate"));
        generateButton.setFocusable(false);
        generateButton
            .setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        generateButton
            .setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(generateButton);

        exportButton.setText(_("Export"));
        exportButton.setFocusable(false);
        exportButton
            .setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(exportButton);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new java.awt.GridLayout(1, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][] { { null, null, null, null },
                    { null, null, null, null }, { null, null, null, null },
                    { null, null, null, null } }, new String[] { "Title 1",
                    "Title 2", "Title 3", "Title 4" }));
        jScrollPane1.setViewportView(jTable1);

        contentPanel.add(jScrollPane1);

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void yearComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearComboBoxItemStateChanged
        if (yearComboBox.getSelectedIndex() >= 0) {
            createMonthItems((Integer) yearComboBox.getSelectedItem());
        }
    }//GEN-LAST:event_yearComboBoxItemStateChanged

    private void monthComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthComboBoxItemStateChanged
        if (monthComboBox.getSelectedIndex() >= 0) {
            createFundsItems((Integer) yearComboBox.getSelectedItem(),
                (Integer) monthComboBox.getSelectedItem());
        }
    }//GEN-LAST:event_monthComboBoxItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton exportButton;
    private javax.swing.JComboBox fundsComboBox;
    private javax.swing.JLabel fundsLabel;
    private javax.swing.JButton generateButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox monthComboBox;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JComboBox yearComboBox;
    private javax.swing.JLabel yearLabel;

    // End of variables declaration//GEN-END:variables
    /*
     * (non-Javadoc)
     * 
     * @see de.aidger.view.tabs.Tab#getTabName()
     */
    @Override
    public String getTabName() {
        // TODO Auto-generated method stub
        return null;
    }

}
