package de.aidger.view.tabs;

import static de.aidger.utils.Translation._;

import javax.swing.JButton;

import de.aidger.model.models.HourlyWage;
import de.aidger.view.tabs.MasterDataViewerTab.MasterDataType;

/**
 * A tab for editing / creating new hourly wages.
 * 
 * @author aidGer Team
 */
@SuppressWarnings("serial")
public class HourlyWageEditorTab extends MasterDataEditorTab {

    /**
     * Constructs a new hourly wage editor tab.
     */
    public HourlyWageEditorTab() {
        super(MasterDataType.HourlyWage);
    }

    /**
     * Constructs a new hourly wage editor tab.
     * 
     * @param hw
     *            the hourly wage that will be edited
     */
    public HourlyWageEditorTab(HourlyWage hw) {
        super(MasterDataType.HourlyWage, hw);

        txtQualification.setText(hw.getQualification());
        // spDate.setValue(hw.getMonth() + "." + hw.getYear());
        txtWage.setText(String.valueOf(hw.getWage()));
    }

    /*
     * (non-Javadoc)
     * 
     * @see de.aidger.view.tabs.MasterDataEditorTab#init()
     */
    @Override
    protected void init() {
        initComponents();
    }

    /*
     * (non-Javadoc)
     * 
     * @see de.aidger.view.tabs.MasterDataEditorTab#setModel()
     */
    @Override
    public void setModel() {
        HourlyWage hw = (HourlyWage) model;

        hw.setQualification(txtQualification.getText());
        hw.setWage(Double.valueOf(txtWage.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblQualification = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblWage = new javax.swing.JLabel();
        txtQualification = new javax.swing.JTextField();
        spDate = new javax.swing.JSpinner();
        txtWage = new javax.swing.JTextField();
        buttons = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        filler = new javax.swing.JLabel();
        filler2 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        lblQualification.setText(_("Qualification"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lblQualification, gridBagConstraints);

        lblDate.setText(_("Date"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lblDate, gridBagConstraints);

        lblWage.setText(_("Wage"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lblWage, gridBagConstraints);

        txtQualification.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(txtQualification, gridBagConstraints);

        spDate.setModel(new javax.swing.SpinnerDateModel());
        spDate
                .setEditor(new javax.swing.JSpinner.DateEditor(spDate,
                        "MM.yyyy"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(spDate, gridBagConstraints);

        txtWage.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(txtWage, gridBagConstraints);

        btnSave.setText(_("Save"));
        buttons.add(btnSave);

        btnCancel.setText(_("Cancel"));
        buttons.add(btnCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(buttons, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weighty = 1.0;
        add(filler, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.weightx = 1.0;
        add(filler2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel buttons;
    private javax.swing.JLabel filler;
    private javax.swing.JLabel filler2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblQualification;
    private javax.swing.JLabel lblWage;
    private javax.swing.JSpinner spDate;
    private javax.swing.JTextField txtQualification;
    private javax.swing.JTextField txtWage;

    // End of variables declaration//GEN-END:variables

    /*
     * (non-Javadoc)
     * 
     * @see de.aidger.view.tabs.MasterDataEditorTab#getButtonCancel()
     */
    @Override
    protected JButton getButtonCancel() {
        return btnCancel;
    }

    /*
     * (non-Javadoc)
     * 
     * @see de.aidger.view.tabs.MasterDataEditorTab#getButtonSave()
     */
    @Override
    protected JButton getButtonSave() {
        return btnSave;
    }

}
