package de.aidger.view.tabs;

import static de.aidger.utils.Translation._;

import java.text.MessageFormat;
import java.util.List;
import java.util.ArrayList;

import de.aidger.model.Runtime;
import de.aidger.model.models.Activity;
import de.aidger.model.models.Assistant;
import de.aidger.model.models.Course;
import de.aidger.model.models.Employment;
import de.aidger.model.models.FinancialCategory;
import de.unistuttgart.iste.se.adohive.exceptions.AdoHiveException;
import de.unistuttgart.iste.se.adohive.model.IActivity;
import de.unistuttgart.iste.se.adohive.model.IAssistant;
import de.unistuttgart.iste.se.adohive.model.IFinancialCategory;

/**
 * A tab which greats the user when the application starts.
 * 
 * @author aidGer Team
 */
@SuppressWarnings("serial")
public class WelcomeTab extends Tab {

    /**
     * Initialises the WelcomeTab class.
     */
    @SuppressWarnings("unchecked")
    public WelcomeTab() {
        initComponents();

        if (Runtime.getInstance().isFirstStart()) {
            statisticsLabel1.setText(_("Currently no statistics are available."));
            statisticsLabel2.setText("");
            statisticsLabel3.setText("");
            statisticsLabel4.setText("");
            statisticsLabel5.setText("");
        } else {
            List<IActivity> activities = null;
            List<IAssistant> assistants = null;
            List<IFinancialCategory> financials = null;
            try {
                activities = (new Activity()).getAll();
                assistants = (new Assistant()).getAll();
                financials = (new FinancialCategory()).getAll();
            } catch (AdoHiveException ex) {
            }

            final List<String> listAct = new ArrayList<String>();
            if (activities != null) {
                int min = activities.size() > 20 ? activities.size() - 20 : 0;

                for (int i = activities.size() - 1; i >= min; --i) {
                    listAct.add(activities.get(i).getContent());
                }
            }

            activitiesList.setModel(new javax.swing.AbstractListModel() {
                String[] strings = listAct.toArray(new String[0]);

                public int getSize() {
                    return strings.length;
                }

                public Object getElementAt(int i) {
                    return strings[i];
                }
            });

            Integer[] qualifications = new Integer[] { 0, 0, 0 };
            for (IAssistant a : assistants) {
                if (a.getQualification().equals("u")) {
                    ++qualifications[0];
                } else if (a.getQualification().equals("c")) {
                    ++qualifications[1];
                } else {
                    ++qualifications[2];
                }
            }

            int funds = 0;
            for (IFinancialCategory f : financials) {
                for (int b : f.getBudgetCosts()) {
                    funds += b;
                }
            }

            try
            {
                statisticsLabel1.setText(MessageFormat.format(
                    _("aidGer has created {0} activities."), new Object[] { activities
                        .size() }));
                statisticsLabel2.setText(MessageFormat.format(
                    _("{0} assistants are working in {1} employments."), new Object[] {
                            assistants.size(), (new Employment()).size() }));
                statisticsLabel3.setText(MessageFormat.format(
                    _("These employments are part of {0} courses."),
                    new Object[] { (new Course()).size() }));
                statisticsLabel4
                    .setText(MessageFormat.format(
                            _("Of the assistants {0} are unchecked, {1} are checked and {2} are bachelors."),
                            (Object[]) qualifications));
                statisticsLabel5.setText(MessageFormat.format(
                    _("They are using funds of {0} Euros."), new Object[] { funds }));
            } catch (AdoHiveException ex) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        activitiesList = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        statisticsLabel1 = new javax.swing.JLabel();
        statisticsLabel2 = new javax.swing.JLabel();
        statisticsLabel3 = new javax.swing.JLabel();
        statisticsLabel4 = new javax.swing.JLabel();
        statisticsLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(_("Welcome to aidGer"));
        jLabel1.setBorder(null);

        jPanel1.setBorder(javax.swing.BorderFactory
            .createTitledBorder(_("Last activities")));

        jScrollPane1.setViewportView(activitiesList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
            jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING).addComponent(
            jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267,
            Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING).addComponent(
            jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336,
            Short.MAX_VALUE));

        jPanel2.setBorder(javax.swing.BorderFactory
            .createTitledBorder(_("Last Changes")));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
            jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 312,
            Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 197,
            Short.MAX_VALUE));

        jPanel3.setBorder(javax.swing.BorderFactory
            .createTitledBorder(_("Statistics")));

        statisticsLabel1.setText("1");

        statisticsLabel2.setText("2");

        statisticsLabel3.setText("3");

        statisticsLabel4.setText("4");

        statisticsLabel5.setText("5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
            jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING).addComponent(
            statisticsLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 312,
            Short.MAX_VALUE).addComponent(statisticsLabel2,
            javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addComponent(statisticsLabel3,
                javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addComponent(statisticsLabel4,
                javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addComponent(statisticsLabel5,
                javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            jPanel3Layout.createSequentialGroup()
                .addComponent(statisticsLabel1).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statisticsLabel2).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statisticsLabel3).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statisticsLabel4).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statisticsLabel5).addContainerGap(
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            javax.swing.GroupLayout.Alignment.TRAILING,
            layout.createSequentialGroup().addContainerGap().addGroup(
                layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.TRAILING).addGroup(
                    layout.createSequentialGroup().addGroup(
                        layout.createParallelGroup(
                            javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE).addComponent(jPanel3,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1,
                            javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1,
                        javax.swing.GroupLayout.DEFAULT_SIZE, 609,
                        Short.MAX_VALUE)).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout.createSequentialGroup().addContainerGap().addComponent(
                jLabel1).addGap(18, 18, 18).addGroup(
                layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                    jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(
                        javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup().addComponent(jPanel2,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE).addPreferredGap(
                            javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel3,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Get the name of the tab.
     * 
     * @return The name
     */
    @Override
    public String getTabName() {
        return _("Welcome to aidGer");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList activitiesList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel statisticsLabel1;
    private javax.swing.JLabel statisticsLabel2;
    private javax.swing.JLabel statisticsLabel3;
    private javax.swing.JLabel statisticsLabel4;
    private javax.swing.JLabel statisticsLabel5;
    // End of variables declaration//GEN-END:variables

}
